name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write # 이 부분 추가

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          npm install
          cd kiosk-system && npm install && cd ..
          cd todo-list && npm install && cd ..

      - name: Build
        run: |
          rm -rf dist
          mkdir dist
          cp index.html dist/
          cd kiosk-system && npm run build && cp -r dist ../dist/kiosk-system && cd ..
          cd todo-list && npm run build && cp -r dist ../dist/todo-list && cd ..

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} #
